//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuryaPrakashNagarajan_BookStore.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int Genre_Id { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
